spring.application.name=notification-service
server.port=8081
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME:}
spring.mail.password=${GMAIL_APP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# RabbitMQ / Queue
# ===============================
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

app.rabbitmq.exchange=${APP_RABBITMQ_EXCHANGE:sale.exchange}
app.rabbitmq.mail-queue=${APP_RABBITMQ_MAIL_QUEUE:mail.queue}
app.rabbitmq.mail-routing-key=${APP_RABBITMQ_MAIL_ROUTING_KEY:mail.send}
