server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Bangkok&characterEncoding=utf8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME:vuthanhtruong1280@gmail.com}
spring.mail.password=${GMAIL_APP_PASSWORD:tumkvmfgjmklmodc}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend.reset-password-url=${APP_FRONTEND_RESET_PASSWORD_URL:http://localhost:4200/reset-password}
app.frontend.orders-url=${APP_FRONTEND_ORDERS_URL:http://localhost:4200/orders}

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}